### PR TITLE
Lots of Additions/Changes

### PR DESCRIPTION
**Pull request by cfis**
See #3.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @cfis, thanks for the PR 👍 Here a few comments (numbered so it's easier to discuss).

1. This is pretty big, so it'll need to be broken up to be merged. It looks like the main functionality that was added was new dataset classes, so maybe we can start there (a single PR for all of them should be fine).

2. I'd like to keep `TensorFlow` as the class name to be consistent with the library name. Technically, the directory should be named `tensor_flow` but I think `tensorflow` looks much nicer so don't want to change it at the moment.

3. We'll likely need to load the protobuf definitions at some point, but want to hold off on that until they are needed for a specific feature.

Let me know your thoughts.

**Comment by cfis** [comment]
On the library name, the problem is the protobuf generated classes use Tensorflow. So you'll end up with two modules in the future -  TensorFlow and Tensorflow.  I think that's a bad place to be and needs to be avoided. Or another way to look at it, Google has already made this choice for us whether we like it or not. I don't think its worth fighting that.

On the protobufs, the OpDef one is super useful. Look at lines 5-16 and 147 in operation.rb. Notice it queries the library for all OpDefs, which are returned as a protobuff. The code then uses that information to correctly sends inputs before executing an op. In the older code, in Utils#execute, there was a hack that said "if this operation is TensorDatasetSlice then do this otherwise that". I then ran into the same problem with the ZipDataset. At that point I went and read what the python code does and found out it uses the opdefs to execute each operation, so updated Ruby to do the same (the number_attr and type_list_attr are the key fields). Note also I added passing tensor attr (that was left as a todo in the original code).

As for the other protobuf classes, I don't mind if we delete them. I figured you had imported all the RawOps so I might as well just go ahead and import all the protobufs (which turned out to be a useful exercise since it showed a bug in the Ruby bindings which I submitted a patch to protobufs).

I do totally get this is a huge amount of code changes. Unfortunately, pushing just the datasets isn't going to work because they depend on other changes (like operation.rb mentioned above) to correctly function.  I have verified that the tests still pass (and added a bunch more), so I don't think I have broken anything.

I could try to split it into a series of pull requests if you really want me to...but I'd rather spend time on working on functions differentiation. 

Anyway, let me know what works for you. I won't dump so much code at once again.

**Comment by ankane** [comment]
Yeah, I think time would be better spent getting differentiation working for now (since that's the main blocker).

Re protobufs: I'm thinking we can create a rake task that pulls them in and namespaces them under `TensorFlow::Protobuf` when needed (if it isn't too painful).

Regardless of the full name, I think users/documentation should use `Tf` so it's easy to port Python examples. At some point, it may make sense to flatten classes (see examples in #1) to make it more Ruby-like.

**Comment by cfis** [comment]
On the protobufs, we will want to include the ones we use in the gem since we don't want to force the user to have to install protobuffs. The files certainly could definitely be generated by a rake task, I just did it by hand because I figure they rarely change if ever. 

The generated files define "module Tensforflow". If it really bugs you, we could search and replace that string in the generated files and change it. Having said that, will it break the serialization back to protobuffs?  Because we will have to do for defining functions (which uses a function def and optdef protobuffs which the c api uses).  So I think its just asking for trouble, but up to you.

Totally good with Tf.

On the differentiation, see my comments in the issue.

**Comment by ankane** [comment]
Agree we want to include protobufs with the gem - the rake task is for gem developers. 

Re "If it really bugs you": if the module name is TensorFlow, we'll want protobufs to match if possible.

**Comment by ankane** [comment]
Let's have any follow up discussion in #3

**Pull request closed without merging**
